apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-aws-for-fluent-bit
  namespace: observability
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /tmp/flb-storage/
        storage.sync  normal
        storage.checksum off
        storage.backlog.mem_limit 5M

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /tmp/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                grep
        Match               kube.*
        Regex               kubernetes.namespace_name z-wallet-prod

    [FILTER]
        Name                record_modifier
        Match               kube.*
        Record              cluster_name prod-eks
        Record              node_name ${NODE_NAME}
        Record              namespace_name ${NAMESPACE}
        Record              environment production

    [OUTPUT]
        Name                es
        Match               kube.*
        Host                ${ELASTICSEARCH_HOST}
        Port                ${ELASTICSEARCH_PORT}
        Index               ${ELASTICSEARCH_INDEX}
        Type                _doc
        HTTP_User           ${ELASTICSEARCH_USER}
        HTTP_Passwd         ${ELASTICSEARCH_PASSWORD}
        tls                 On
        tls.verify          Off
        Logstash_Format     On
        Logstash_Prefix     z-wallet-prod
        Logstash_DateFormat %Y.%m.%d
        Replace_Dots        On
        Retry_Limit         6
