apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-elasticsearch
  namespace: observability
  labels:
    app: fluent-bit-elasticsearch
spec:
  selector:
    matchLabels:
      app: fluent-bit-elasticsearch
  template:
    metadata:
      labels:
        app: fluent-bit-elasticsearch
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.32.2.20240516
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 100m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: host
        - name: ELASTICSEARCH_PORT
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: port
        - name: ELASTICSEARCH_INDEX
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: index
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: password
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::190749975524:role/prod-eks-fluent-bit"
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: "regional"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-1"
        - name: AWS_REGION
          value: "ap-northeast-1"
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: aws-iam-token
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          readOnly: true
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-simple-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: aws-iam-token
        projected:
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
