apiVersion: velero.io/v1
kind: Backup
metadata:
  name: gitlab-manual-backup
  namespace: velero
spec:
  defaultVolumesToFsBackup: true
  includedNamespaces:
    - gitlab
  storageLocation: default
  ttl: 168h0m0s # 7 days

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: gitlab-daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - gitlab
    storageLocation: default
    ttl: 720h0m0s # 30 days

