# Velero Helm Chart Values
# Cấu hình cho backup namespace gitlab

# Namespace cho Velero
namespaceOverride: "velero"

# Service Account
serviceAccount:
  server:
    create: true
    name: velero
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::190749975524:role/prod-eks-velero"

# Configuration
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: "eks-prod-velero-backups-190749975524"
      config:
        region: "ap-northeast-1"
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: "ap-northeast-1"

# Install AWS plugin via initContainer
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# Credentials
credentials:
  useSecret: false

# Node Agent (thay thế restic)
nodeAgent:
  enabled: true

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Tolerations để chạy trên tất cả nodes
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# Node selector
nodeSelector: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

# Metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Disable nếu chưa có Prometheus

# Logging
logLevel: info

# Features
features: "EnableCSI"