apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roles.albControllerArn is required" .Values.roles.albControllerArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roles.externalDnsArn is required" .Values.roles.externalDnsArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roles.clusterAutoscalerArn is required" .Values.roles.clusterAutoscalerArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roles.fluentBitArn is required" .Values.roles.fluentBitArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roles.veleroArn is required" .Values.roles.veleroArn | quote }}


