apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.nameOverride }}-{{ .Values.env }}
    tier: {{ .Values.env }}-backend
  name: {{ .Values.nameOverride }}-{{ .Values.env }}
  namespace : {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}-{{ .Values.env }}
      tier: {{ .Values.env }}-backend
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}-{{ .Values.env }}
        tier: {{ .Values.env }}-backend
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceAccount.name }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      {{- if .Values.tolerations.items }}
      tolerations:
        {{- toYaml .Values.tolerations.items | nindent 8 }}
      {{- end }}
      {{- end }}        
      containers:
      - name: {{ .Values.nameOverride }}-{{ .Values.env }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"       
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- if .Values.service.ports }}
        {{- range .Values.service.ports }}
        - name: {{ .name }}
          protocol: {{ default "TCP" .protocol }}
          containerPort: {{ .targetPort }}
        {{- end }}
        {{- else }}
        - name: {{ .Values.service.nameWebsocket }}
          protocol: TCP            
          containerPort: {{ .Values.service.targetPortWebsocket }}
        - name: {{ .Values.service.nameSocket }}
          protocol: TCP            
          containerPort: {{ .Values.service.targetPortSocket }}      
        - name: {{ .Values.service.nameWeb }}
          protocol: TCP            
          containerPort: {{ .Values.service.targetPortWeb }}
        - name: {{ .Values.service.nameJmx }}
          protocol: TCP            
          containerPort: {{ .Values.service.targetPortJmx }}                           
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- if .Values.command }}
        command:
          {{- toYaml .Values.command | nindent 10 }}
        {{- end }}
        
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
      

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
