{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.nameOverride }}-default-deny
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.defaultDenyIngress }}
  ingress: []
  {{- end }}
  {{- if .Values.networkPolicy.defaultDenyEgress }}
  egress: []
  {{- end }}
{{- end }}

